
//FILE SYSTEM
export const CREATE_FOLDER = 'CREATE_FOLDER'
export const GET_FOLDERS = 'GET_FOLDERS'
export const GET_FILES_INSIDE = 'GET_FILES_INSIDE'
export const GET_ONE_FILE = 'GET_ONE_FILE'
export const SAVE_FILE = 'SAVE_FILE'
export const SET_STATUS = 'SET_STATUS' 
//CREATE FILES
export const SEND_IMAGE = 'SEND_IMAG'
export const SEND_HTML = 'SEND_HTML'
export const EDIT_FILE = 'EDIT_FILE'
export const CREATE_FILE = 'CREATE_FILE'
export const DELETE_FILE= 'DELETE_FILE'
//AUTH
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGIN = 'LOGIN'
export const LOAD_PERMISSION = 'LOAD_PERMISSION'
//SEarch
export const PUSH_FILES_TO_SEARCH = 'PUSH_FILES_TO_SEARCH'
export const PUSH_SECTIONS_TO_SEARCH = 'PUSH_SECTIONS_TO_SEARCH'